In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./경진대회용 사출성형기 데이터셋_labeled.csv")

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7996 entries, 0 to 7995
Data columns (total 45 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   _id                       7996 non-null   object
 1   TimeStamp                 7996 non-null   object
 2   PART_FACT_PLAN_DATE       7996 non-null   object
 3   PART_FACT_SERIAL          7996 non-null   int64
 4   PART_NAME                 7996 non-null   object
 5   EQUIP_CD                  7996 non-null   object
 6   EQUIP_NAME                7996 non-null   object
 7   PassOrFail                7996 non-null   object
 8   Reason                    71 non-null     object
 9   Injection_Time            7996 non-null   float64
 10  Filling_Time              7996 non-null   float64
 11  Plasticizing_Time         7996 non-null   float64
 12  Cycle_Time                7996 non-null   float64
 13  Clamp_Close_Time          7996 non-null   float64
 14  Cushion_Position          7996 non-null   float64
 15  Switch_Over_Position      7996 non-null   float64
 16  Plasticizing_Position     7996 non-null   float64
 17  Clamp_Open_Position       7996 non-null   float64
 18  Max_Injection_Speed       7996 non-null   float64
 19  Max_Screw_RPM             7996 non-null   float64
 20  Average_Screw_RPM         7996 non-null   float64
 21  Max_Injection_Pressure    7996 non-null   float64
 22  Max_Switch_Over_Pressure  7996 non-null   float64
 23  Max_Back_Pressure         7996 non-null   float64
 24  Average_Back_Pressure     7996 non-null   float64
 25  Barrel_Temperature_1      7996 non-null   float64
 26  Barrel_Temperature_2      7996 non-null   float64
 27  Barrel_Temperature_3      7996 non-null   float64
 28  Barrel_Temperature_4      7996 non-null   float64
 29  Barrel_Temperature_5      7996 non-null   float64
 30  Barrel_Temperature_6      7996 non-null   float64
 31  Barrel_Temperature_7      7996 non-null   float64
 32  Hopper_Temperature        7996 non-null   float64
 33  Mold_Temperature_1        7996 non-null   float64
 34  Mold_Temperature_2        7996 non-null   float64
 35  Mold_Temperature_3        7996 non-null   float64
 36  Mold_Temperature_4        7996 non-null   float64
 37  Mold_Temperature_5        7996 non-null   float64
 38  Mold_Temperature_6        7996 non-null   float64
 39  Mold_Temperature_7        7996 non-null   float64
 40  Mold_Temperature_8        7996 non-null   float64
 41  Mold_Temperature_9        7996 non-null   float64
 42  Mold_Temperature_10       7996 non-null   float64
 43  Mold_Temperature_11       7996 non-null   float64
 44  Mold_Temperature_12       7996 non-null   float64
dtypes: float64(36), int64(1), object(8)
memory usage: 2.7+ MB

,PART_FACT_SERIAL,Injection_Time,Filling_Time,Plasticizing_Time,Cycle_Time,Clamp_Close_Time,Cushion_Position,Switch_Over_Position,Plasticizing_Position,Clamp_Open_Position,...,Mold_Temperature_3,Mold_Temperature_4,Mold_Temperature_5,Mold_Temperature_6,Mold_Temperature_7,Mold_Temperature_8,Mold_Temperature_9,Mold_Temperature_10,Mold_Temperature_11,Mold_Temperature_12
count,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,...,7996.000000,7996.000000,7996.0,7996.0,7996.0,7996.0,7996.0,7996.0,7996.0,7996.0
mean,11.248749,8.242189,3.896309,16.209505,59.900902,7.064088,653.408195,0.330320,66.054484,544.244111,...,22.145260,23.522574,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,5.005191,3.107724,1.284451,1.443720,0.885680,0.136595,10.165106,14.654889,5.418233,236.351404,...,1.177468,1.356586,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,2.000000,1.050000,0.930000,10.920000,58.840000,5.160000,11.100000,0.000000,53.549999,4.630000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,9.000000,9.520000,4.400000,16.580000,59.520000,7.110000,653.429993,0.000000,68.250000,647.989990,...,21.400000,22.700001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,10.000000,9.560000,4.440000,16.799999,59.520000,7.120000,653.440002,0.000000,68.339996,647.989990,...,22.000000,23.400000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,13.000000,9.590000,4.470000,16.889999,59.560001,7.120000,653.450012,0.000000,68.489998,647.989990,...,22.900000,24.200001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,24.000000,16.309999,8.270000,21.120001,66.860001,7.180000,655.080017,655.309998,68.860001,883.700012,...,25.299999,27.799999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df["EQUIP_NAME"].value_counts()

EQUIP_NAME
650톤-우진2호기    7992
1800TON-우진       2
650톤-우진          2
Name: count, dtype: int64

In [4]:
df = df.drop(columns=["Mold_Temperature_1", "Mold_Temperature_2"])

In [5]:
df = df.drop(columns=['Mold_Temperature_5',
       'Mold_Temperature_6', 'Mold_Temperature_7', 'Mold_Temperature_8',
       'Mold_Temperature_9', 'Mold_Temperature_10', 'Mold_Temperature_11',
       'Mold_Temperature_12'])

In [6]:
print(df.columns)
df.describe()

Index(['_id', 'TimeStamp', 'PART_FACT_PLAN_DATE', 'PART_FACT_SERIAL',
       'PART_NAME', 'EQUIP_CD', 'EQUIP_NAME', 'PassOrFail', 'Reason',
       'Injection_Time', 'Filling_Time', 'Plasticizing_Time', 'Cycle_Time',
       'Clamp_Close_Time', 'Cushion_Position', 'Switch_Over_Position',
       'Plasticizing_Position', 'Clamp_Open_Position', 'Max_Injection_Speed',
       'Max_Screw_RPM', 'Average_Screw_RPM', 'Max_Injection_Pressure',
       'Max_Switch_Over_Pressure', 'Max_Back_Pressure',
       'Average_Back_Pressure', 'Barrel_Temperature_1', 'Barrel_Temperature_2',
       'Barrel_Temperature_3', 'Barrel_Temperature_4', 'Barrel_Temperature_5',
       'Barrel_Temperature_6', 'Barrel_Temperature_7', 'Hopper_Temperature',
       'Mold_Temperature_3', 'Mold_Temperature_4'],
      dtype='object')

,PART_FACT_SERIAL,Injection_Time,Filling_Time,Plasticizing_Time,Cycle_Time,Clamp_Close_Time,Cushion_Position,Switch_Over_Position,Plasticizing_Position,Clamp_Open_Position,...,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Barrel_Temperature_7,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
count,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,...,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000,7996.000000
mean,11.248749,8.242189,3.896309,16.209505,59.900902,7.064088,653.408195,0.330320,66.054484,544.244111,...,277.457016,276.706015,276.443122,271.075388,256.507403,230.763295,0.009105,66.458742,22.145260,23.522574
std,5.005191,3.107724,1.284451,1.443720,0.885680,0.136595,10.165106,14.654889,5.418233,236.351404,...,6.101631,4.088561,4.099543,2.675956,3.837589,1.945383,0.575642,2.577198,1.177468,1.356586
min,2.000000,1.050000,0.930000,10.920000,58.840000,5.160000,11.100000,0.000000,53.549999,4.630000,...,0.000000,244.800003,245.000000,239.600006,235.300003,220.000000,0.000000,0.000000,0.000000,0.000000
25%,9.000000,9.520000,4.400000,16.580000,59.520000,7.110000,653.429993,0.000000,68.250000,647.989990,...,275.899994,275.000000,274.899994,269.799988,254.899994,229.899994,0.000000,65.400002,21.400000,22.700001
50%,10.000000,9.560000,4.440000,16.799999,59.520000,7.120000,653.440002,0.000000,68.339996,647.989990,...,276.200012,275.399994,275.000000,270.700012,255.000000,230.100006,0.000000,66.699997,22.000000,23.400000
75%,13.000000,9.590000,4.470000,16.889999,59.560001,7.120000,653.450012,0.000000,68.489998,647.989990,...,276.600006,275.700012,275.399994,271.399994,255.399994,230.199997,0.000000,67.599998,22.900000,24.200001
max,24.000000,16.309999,8.270000,21.120001,66.860001,7.180000,655.080017,655.309998,68.860001,883.700012,...,287.100006,286.500000,285.799988,276.799988,270.399994,264.299988,36.400002,70.599998,25.299999,27.799999

In [1]:
df.info()

NameError: name 'df' is not defined

In [7]:
df.head()

,_id,TimeStamp,PART_FACT_PLAN_DATE,PART_FACT_SERIAL,PART_NAME,EQUIP_CD,EQUIP_NAME,PassOrFail,Reason,Injection_Time,...,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Barrel_Temperature_7,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
0,5f8928bb9c0189cc666ef19b,2020-10-16 04:57:47,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,...,276.500000,274.700012,274.799988,269.200012,255.000000,229.699997,0.0,66.300003,24.799999,27.5
1,5f8928de9c0189cc666ef20b,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.60,...,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,0.0,67.199997,24.799999,27.6
2,5f8928df9c0189cc666ef213,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.60,...,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,0.0,67.199997,24.799999,27.6
3,5f8928f39c0189cc666ef25e,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.59,...,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,0.0,66.900002,25.000000,27.6
4,5f8928f59c0189cc666ef265,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,...,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,0.0,66.900002,25.000000,27.6

In [8]:
# 피어슨 스피어만 상관계수 확인
from scipy.stats import spearmanr, pearsonr

X = df["TimeStamp"]
y = df["PassOrFail"]

s, p = spearmanr(X, y)
s, p

(0.068072271885991, 1.1070094226088288e-09)

In [9]:
df['TimeStamp'] = pd.to_datetime(df['TimeStamp'])

In [10]:
df.iloc[:,:]

,_id,TimeStamp,PART_FACT_PLAN_DATE,PART_FACT_SERIAL,PART_NAME,EQUIP_CD,EQUIP_NAME,PassOrFail,Reason,Injection_Time,...,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Barrel_Temperature_7,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
0,5f8928bb9c0189cc666ef19b,2020-10-16 04:57:47,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,...,276.500000,274.700012,274.799988,269.200012,255.000000,229.699997,0.0,66.300003,24.799999,27.5
1,5f8928de9c0189cc666ef20b,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.60,...,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,0.0,67.199997,24.799999,27.6
2,5f8928df9c0189cc666ef213,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.60,...,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,0.0,67.199997,24.799999,27.6
3,5f8928f39c0189cc666ef25e,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.59,...,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,0.0,66.900002,25.000000,27.6
4,5f8928f59c0189cc666ef265,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,...,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,0.0,66.900002,25.000000,27.6

In [11]:
df['TimeStamp'] = pd.to_datetime(df['TimeStamp'])

In [12]:
df.columns

Index(['_id', 'TimeStamp', 'PART_FACT_PLAN_DATE', 'PART_FACT_SERIAL',
       'PART_NAME', 'EQUIP_CD', 'EQUIP_NAME', 'PassOrFail', 'Reason',
       'Injection_Time', 'Filling_Time', 'Plasticizing_Time', 'Cycle_Time',
       'Clamp_Close_Time', 'Cushion_Position', 'Switch_Over_Position',
       'Plasticizing_Position', 'Clamp_Open_Position', 'Max_Injection_Speed',
       'Max_Screw_RPM', 'Average_Screw_RPM', 'Max_Injection_Pressure',
       'Max_Switch_Over_Pressure', 'Max_Back_Pressure',
       'Average_Back_Pressure', 'Barrel_Temperature_1', 'Barrel_Temperature_2',
       'Barrel_Temperature_3', 'Barrel_Temperature_4', 'Barrel_Temperature_5',
       'Barrel_Temperature_6', 'Barrel_Temperature_7', 'Hopper_Temperature',
       'Mold_Temperature_3', 'Mold_Temperature_4'],
      dtype='object')

In [13]:
df = df.drop(columns=['_id', 'PART_FACT_PLAN_DATE', 'PART_FACT_SERIAL',
                   'PART_NAME', 'EQUIP_NAME', 'Reason'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7996 entries, 0 to 7995
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TimeStamp                 7996 non-null   datetime64[ns]
 1   EQUIP_CD                  7996 non-null   object
 2   PassOrFail                7996 non-null   object
 3   Injection_Time            7996 non-null   float64
 4   Filling_Time              7996 non-null   float64
 5   Plasticizing_Time         7996 non-null   float64
 6   Cycle_Time                7996 non-null   float64
 7   Clamp_Close_Time          7996 non-null   float64
 8   Cushion_Position          7996 non-null   float64
 9   Switch_Over_Position      7996 non-null   float64
 10  Plasticizing_Position     7996 non-null   float64
 11  Clamp_Open_Position       7996 non-null   float64
 12  Max_Injection_Speed       7996 non-null   float64
 13  Max_Screw_RPM             7996 non-null   float64
 14  Average_Screw_RPM         7996 non-null   float64
 15  Max_Injection_Pressure    7996 non-null   float64
 16  Max_Switch_Over_Pressure  7996 non-null   float64
 17  Max_Back_Pressure         7996 non-null   float64
 18  Average_Back_Pressure     7996 non-null   float64
 19  Barrel_Temperature_1      7996 non-null   float64
 20  Barrel_Temperature_2      7996 non-null   float64
 21  Barrel_Temperature_3      7996 non-null   float64
 22  Barrel_Temperature_4      7996 non-null   float64
 23  Barrel_Temperature_5      7996 non-null   float64
 24  Barrel_Temperature_6      7996 non-null   float64
 25  Barrel_Temperature_7      7996 non-null   float64
 26  Hopper_Temperature        7996 non-null   float64
 27  Mold_Temperature_3        7996 non-null   float64
 28  Mold_Temperature_4        7996 non-null   float64
dtypes: datetime64[ns](1), float64(26), object(2)
memory usage: 1.8+ MB

In [15]:
df["PassOrFail"] = df["PassOrFail"].replace("Y", 0).replace("N", 1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_2444\750960889.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["PassOrFail"] = df["PassOrFail"].replace("Y", 0).replace("N", 1)

In [16]:
df["EQUIP_CD"].value_counts()

EQUIP_CD
S14    7992
S01       2
S12       2
Name: count, dtype: int64

In [17]:
df_encoded = pd.get_dummies(df, columns=['EQUIP_CD'], prefix='EQUIP_CD')

# 결과 확인
print(df_encoded.head())

            TimeStamp  PassOrFail  Injection_Time  Filling_Time  \
0 2020-10-16 04:57:47           0            9.59          4.47
1 2020-10-16 04:58:48           0            9.60          4.48
2 2020-10-16 04:58:48           0            9.60          4.48
3 2020-10-16 04:59:48           0            9.59          4.48
4 2020-10-16 04:59:48           0            9.59          4.48

   Plasticizing_Time  Cycle_Time  Clamp_Close_Time  Cushion_Position  \
0              16.92   59.520000              7.13        653.409973
1              16.91   59.580002              7.13        653.409973
2              16.91   59.580002              7.13        653.409973
3              16.91   59.560001              7.13        653.419983
4              16.91   59.560001              7.13        653.419983

   Switch_Over_Position  Plasticizing_Position  ...  Barrel_Temperature_4  \
0                   0.0              68.849998  ...            269.200012
1                   0.0              68.839996  ...            270.799988
2                   0.0              68.839996  ...            270.799988
3                   0.0              68.839996  ...            271.100006
4                   0.0              68.839996  ...            271.100006

   Barrel_Temperature_5  Barrel_Temperature_6  Barrel_Temperature_7  \
0            255.000000            229.699997                   0.0
1            254.699997            229.500000                   0.0
2            254.699997            229.500000                   0.0
3            254.899994            230.000000                   0.0
4            254.899994            230.000000                   0.0

   Hopper_Temperature  Mold_Temperature_3  Mold_Temperature_4  EQUIP_CD_S01  \
0           66.300003           24.799999                27.5         False
1           67.199997           24.799999                27.6         False
2           67.199997           24.799999                27.6         False
3           66.900002           25.000000                27.6         False
4           66.900002           25.000000                27.6         False

   EQUIP_CD_S12  EQUIP_CD_S14
0         False          True
1         False          True
2         False          True
3         False          True
4         False          True

[5 rows x 31 columns]

In [18]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7996 entries, 0 to 7995
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TimeStamp                 7996 non-null   datetime64[ns]
 1   PassOrFail                7996 non-null   int64
 2   Injection_Time            7996 non-null   float64
 3   Filling_Time              7996 non-null   float64
 4   Plasticizing_Time         7996 non-null   float64
 5   Cycle_Time                7996 non-null   float64
 6   Clamp_Close_Time          7996 non-null   float64
 7   Cushion_Position          7996 non-null   float64
 8   Switch_Over_Position      7996 non-null   float64
 9   Plasticizing_Position     7996 non-null   float64
 10  Clamp_Open_Position       7996 non-null   float64
 11  Max_Injection_Speed       7996 non-null   float64
 12  Max_Screw_RPM             7996 non-null   float64
 13  Average_Screw_RPM         7996 non-null   float64
 14  Max_Injection_Pressure    7996 non-null   float64
 15  Max_Switch_Over_Pressure  7996 non-null   float64
 16  Max_Back_Pressure         7996 non-null   float64
 17  Average_Back_Pressure     7996 non-null   float64
 18  Barrel_Temperature_1      7996 non-null   float64
 19  Barrel_Temperature_2      7996 non-null   float64
 20  Barrel_Temperature_3      7996 non-null   float64
 21  Barrel_Temperature_4      7996 non-null   float64
 22  Barrel_Temperature_5      7996 non-null   float64
 23  Barrel_Temperature_6      7996 non-null   float64
 24  Barrel_Temperature_7      7996 non-null   float64
 25  Hopper_Temperature        7996 non-null   float64
 26  Mold_Temperature_3        7996 non-null   float64
 27  Mold_Temperature_4        7996 non-null   float64
 28  EQUIP_CD_S01              7996 non-null   bool
 29  EQUIP_CD_S12              7996 non-null   bool
 30  EQUIP_CD_S14              7996 non-null   bool
dtypes: bool(3), datetime64[ns](1), float64(26), int64(1)
memory usage: 1.7 MB

In [19]:
col_list = df_encoded.columns
col_list

Index(['TimeStamp', 'PassOrFail', 'Injection_Time', 'Filling_Time',
       'Plasticizing_Time', 'Cycle_Time', 'Clamp_Close_Time',
       'Cushion_Position', 'Switch_Over_Position', 'Plasticizing_Position',
       'Clamp_Open_Position', 'Max_Injection_Speed', 'Max_Screw_RPM',
       'Average_Screw_RPM', 'Max_Injection_Pressure',
       'Max_Switch_Over_Pressure', 'Max_Back_Pressure',
       'Average_Back_Pressure', 'Barrel_Temperature_1', 'Barrel_Temperature_2',
       'Barrel_Temperature_3', 'Barrel_Temperature_4', 'Barrel_Temperature_5',
       'Barrel_Temperature_6', 'Barrel_Temperature_7', 'Hopper_Temperature',
       'Mold_Temperature_3', 'Mold_Temperature_4', 'EQUIP_CD_S01',
       'EQUIP_CD_S12', 'EQUIP_CD_S14'],
      dtype='object')

In [25]:
for col in col_list[2:]:
    X = df_encoded[col]
    y = df_encoded["PassOrFail"]
    print(col)
    s, p = spearmanr(X, y)
    print(s, p)

Injection_Time
-0.01368938252231656 0.2209614988144394
Filling_Time
-0.013083786662651075 0.24207179800121598
Plasticizing_Time
-0.050395003260446276 6.528779754054665e-06
Cycle_Time
0.07621444969064053 8.854963280389467e-12
Clamp_Close_Time
-0.004808474059099401 0.6672605847035351
Cushion_Position
0.01436463034348373 0.19901749216659628
Switch_Over_Position
-0.0025937716987743478 0.8166155936377075
Plasticizing_Position
0.014084487077239617 0.20792004338033107
Clamp_Open_Position
-0.07474455544262135 2.201381408642633e-11
Max_Injection_Speed
0.01828484914885477 0.10206607916004479
Max_Screw_RPM
0.0538877884206 1.4254339969631123e-06
Average_Screw_RPM
0.05732040246724916 2.9124427637176705e-07
Max_Injection_Pressure
0.07549241764798881 1.3880374141721834e-11
Max_Switch_Over_Pressure
0.0022393498993606557 0.8413144623420628
Max_Back_Pressure
0.06180677228414959 3.180331748040626e-08
Average_Back_Pressure
0.0688204688918087 7.261044509940743e-10
Barrel_Temperature_1
0.041486374539516195 0.00020665111373604732
Barrel_Temperature_2
0.035349699624049484 0.0015697146109582563
Barrel_Temperature_3
0.07108965711863087 1.966673729005636e-10
Barrel_Temperature_4
0.06098442380668806 4.829501341075019e-08
Barrel_Temperature_5
0.07561109817292808 1.289548861590181e-11
Barrel_Temperature_6
0.03082236587979274 0.005844668658381525
Barrel_Temperature_7
-0.0014971401756677964 0.8935180634689837
Hopper_Temperature
-0.07050716036173969 2.760843099552138e-10
Mold_Temperature_3
0.016160099552646228 0.14848309003930335
Mold_Temperature_4
0.018599904523705652 0.09629363929479032
EQUIP_CD_S01
-0.0014971401756677964 0.8935180634689837
EQUIP_CD_S12
-0.0014971401756677964 0.8935180634689837
EQUIP_CD_S14
0.002117540849047826 0.849840559457161

In [24]:
temp_list = [1,2,3,4,5,6,7,8,9,10]
temp_list[2:-1]

[3, 4, 5, 6, 7, 8, 9]